version: '3.9'
services:
  app:
    build:
      context: ./backend
    container_name: backend_container
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      RAILS_ENV: development
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./backend:/app
    networks:
      - elastic

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: es_container
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/elastic-cert.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/elastic-cert.crt
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/elastic-cert.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/elastic-cert.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/elastic-cert.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/elastic-cert.crt
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./backend/config/certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9200:9200"
    networks:
      - elastic
# TODO: volumesも本番環境用を追加する必要があるかもしれない
volumes:
  es_data:
    driver: local
  db_data:
    driver: local

networks:
  elastic:
    driver: bridge
